name: Airtable Sync
on:
  schedule:
    - cron:  '30 12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: repub/dlc-scholarbot@v0.1
        env:
          AIRTABLE_APIKEY: ${{secrets.AIRTABLE_APIKEY}}
          AIRTABLE_BASEID: ${{secrets.AIRTABLE_BASEID}}
