# Workflow to update ScholarSphere Curation records in Airtable
name: Airtable Sync
on:
  schedule:
    - cron:  '30 12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./action/action.yml
        env:
          AIRTABLE_APIKEY: ${{secrets.AIRTABLE_APIKEY}}
          AIRTABLE_BASEID: ${{secrets.AIRTABLE_BASEID}}
